title : Blog Title
tagline: Blog Tagline
author :
  name : Chris Brauchli
  email : chris@brauchli.me
  github : cbrauchli
  twitter : cbrauchli
  # feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
